### ISSUE TITLE
https://github.com/Rommanski/CoinsDiffusion/blob/master/europe_module.py#L6

### ISSUE THREAD

**Issue by AngelinaMelek** [Rommanski/CoinsDiffusion#7]
def __init__(self):
        self.europeMap = [[None for i in range(MAP_SIZE)] for j in range(MAP_SIZE)]
        pass
Прошу додати коментар, так як не зовсім зрозуміла що робить ця функція

**Comment by Rommanski** [comment]
@AngelinaMelek  I have added comments in [PR](https://github.com/Rommanski/CoinsDiffusion/pull/10). Please review. I'll merge him if you confirm that everything is clear now.
