### ISSUE TITLE
https://github.com/Rommanski/CoinsDiffusion/blob/master/europe_module.py#L25

### ISSUE THREAD

**Issue by AngelinaMelek** [Rommanski/CoinsDiffusion#8]
Що позначає "horizont"?
Прошу додати пояснення

**Comment by Rommanski** [comment]
@AngelinaMelek  I have added comments in [PR](https://github.com/Rommanski/CoinsDiffusion/pull/10). Please review. I'll merge him if you confirm that everything is clear now.
